version: '3'

services:
  myapp:
    build: .
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
